### ISSUE TITLE
Using a version number range results in a TypeError

### ISSUE THREAD

**Issue by markstory** [nathanhleung/install-peerdeps#25]
I attempted to use a version number range with `install-peerdeps` and got a TypeError. To reproduce you can do the following:

```
 install-peerdeps --yarn eslint-plugin-node@^6.x
install-peerdeps v1.6.0
/tool/node_modules/install-peerdeps/lib/helpers.js:34
    packageName = parsed[1];
                        ^

TypeError: Cannot read property '1' of null
    at parsePackageString (/tool/node_modules/install-peerdeps/lib/helpers.js:34:25)
    at Object.<anonymous> (/tool/node_modules/install-peerdeps/lib/cli.js:78:59)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I was hoping to have a version number resolved based on the constraint as `npm` and `yarn` would do.

**Comment by markstory** [comment]
Thank you!
